greetings-gradle/2.14.0-J9/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.14.0/gradle/wrapper/gradle-wrapper.properties

use gradle 4.6

---

greetings-gradle/2.14.0-J10/build.gradle
greetings-gradle/2.14.0-J10/org.xtext.example.mydsl/build.gradle
greetings-gradle/2.14.0-J9/build.gradle
greetings-gradle/2.14.0-J9/org.xtext.example.mydsl/build.gradle
greetings-gradle/2.14.0/build.gradle
greetings-gradle/2.14.0/org.xtext.example.mydsl/build.gradle
greetings-maven/2.12.0/org.xtext.example.mydsl/pom.xml
greetings-maven/2.12.0/pom.xml
greetings-maven/2.13.0/org.xtext.example.mydsl/pom.xml
greetings-maven/2.13.0/pom.xml
greetings-maven/2.14.0-J10/org.xtext.example.mydsl/pom.xml
greetings-maven/2.14.0-J10/pom.xml
greetings-maven/2.14.0/org.xtext.example.mydsl/pom.xml
greetings-maven/2.14.0/pom.xml
greetings-tycho/2.14.0-J9/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.14.0-J9/pom.xml
greetings-tycho/2.14.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.14.0/pom.xml

build against final 2.14 and fix sign bug

---

.travis.yml

fixed java 10 cert issue

---

.travis.yml

fixed xvfb

---

domainmodel/2.16.0/org.eclipse.xtext.example.domainmodel.ide/pom.xml

use latest lsp4j

---

greetings-gradle/2.16.0-J10/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.16.0-J9/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.16.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.16.0-J10/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.16.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.16.0-J10/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.16.0-J10/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.16.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.16.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to 2.16 final

---

domainmodel/2.16.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.16.0-J10/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.16.0/org.xtext.example.mydsl.parent/pom.xml

switched to tycho 1.3 final

---

.project

added missing .project

---

greetings-tycho/2.17.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

use 2019-03 update site

---

domainmodel/2.17.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.17.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
domainmodel/2.17.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-gradle/2.17.0/org.xtext.example.mydsl/build.gradle
greetings-maven/2.17.0/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/pom.xml
greetings-maven/2.17.0/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.17.0/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.17.0/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.17.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.17.0/org.xtext.example.mydsl/pom.xml

update to mwe 2.10 m2

---

integrationtests/org.eclipse.xtext.swtbot.tests/pom.xml
integrationtests/pom.xml

#36 Do not ignore test failures any more.
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

#36 Do not ignore test failures any more.

---

domainmodel/2.17.0/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/navigation/DomainmodelHyperlinkHelper.java

- Update the DomainmodelHyperlinkHelper class.

Update the domainmodel/2.17.0: apply changes from the latest Xtext 2.17

---

greetings-tycho/2.17.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.17.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

https://github.com/eclipse/xtext-core/issues/1054issues/1054

fixed tp according to proposed patch in xtext-core

---

greetings-gradle/2.17.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.17.0/org.xtext.example.mydsl.parent/build.gradle

updated to xtext gradle plugin 2.0.4
(reflects changes for https://github.com/eclipse/xtext-core/issues/1053)

updated to xtext gradle plugin 2.0.4

---

domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
greetings-tycho/2.18.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.18.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

replaced asm with 7.1 due orbit changes

replaced asm with 7.1 due orbit changes

---

domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-luna-linux.target
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-luna-linux.tpd
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-luna-macos.target
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-luna-macos.tpd
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-mars-linux.target
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-mars-linux.tpd
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-mars-macos.target
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-mars-macos.tpd
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-oxygen.target
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-oxygen.tpd
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.target
domainmodel/2.14.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel-photon.tpd
domainmodel/2.16.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.16.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.16.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
domainmodel/2.17.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.17.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
greetings-tycho/2.17.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.17.0/org.xtext.example.mydsl.parent/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.17.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

fixed target platforms for older releases

fixed target platforms for older releases

---

greetings-gradle/2.18.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties

regen example for 2.18

---

domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF

recreated 2.18 domainmodel

---

domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.ide/META-INF/MANIFEST.MF
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.ide/pom.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/feature/feature.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/feature/pom.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/repository/pom.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.releng/tp/pom.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.tests/pom.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.ui.tests/pom.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.ui/META-INF/MANIFEST.MF
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel.ui/pom.xml
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
domainmodel/2.18.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-gradle/2.18.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.18.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.18.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.18.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.18.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.18.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.18.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.18.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

updated to 2.18 release #59

---

domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd

fixed guava version

---

domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.19.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.19.0/org.xtext.example.mydsl/pom.xml
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

fixed mwe on 2.19

---

greetings-gradle/2.19.0/org.xtext.example.mydsl.parent/build.gradle

bumped xtext gradle plugin for 2.19

bumped xtext gradle plugin for 2.19

---

domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.19.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext1475] use 2019-09 in latest target platform

---

domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.tpd
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.19.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

recreated 2.19 samples

---

greetings-gradle/2.19.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.19.0/org.xtext.example.mydsl.parent/gradlew
greetings-gradle/2.19.0/org.xtext.example.mydsl.parent/gradlew.bat

[eclipse/xtext#1489] update to gradle 5.5

---

greetings-gradle/2.19.0/org.xtext.example.mydsl.parent/build.gradle

bumped xtext gradle plugin to 2.0.7

---

greetings-gradle/2.19.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.19.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.19.0-J11/org.xtext.example.mydsl.parent/gradlew
greetings-gradle/2.19.0-J11/org.xtext.example.mydsl.parent/gradlew.bat
greetings-maven/2.19.0-J11/org.xtext.example.mydsl.ide/pom.xml
greetings-maven/2.19.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.19.0-J11/org.xtext.example.mydsl/pom.xml
greetings-maven/2.19.0/org.xtext.example.mydsl.ide/pom.xml
greetings-maven/2.19.0/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.19.0/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.ui.tests/META-INF/MANIFEST.MF
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl/.launch/Launch Runtime Eclipse.launch
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.19.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.19.0/org.xtext.example.mydsl.ui.tests/META-INF/MANIFEST.MF
greetings-tycho/2.19.0/org.xtext.example.mydsl/.launch/Launch Runtime Eclipse.launch
greetings-tycho/2.19.0/org.xtext.example.mydsl/pom.xml

recreated 2.19 projects

---

.travis.yml

removed obsolete java 9 jdk

---

greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.19.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

updated to junit 5.5

---

greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.19.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

adjusted to timestamp changes in orbit

---

domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/FoldingTest.xtend
domainmodel/2.19.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-gradle/2.19.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.19.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.19.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.19.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.19.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.19.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.19.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#1539] prepare 2.19 release tests

[eclipse/xtext#1539] prepare 2.19 release tests

---

.travis.yml
scripts/domainmodel-2.20.sh
scripts/greetings-gradle-2.20-J11.sh
scripts/greetings-gradle-2.20.sh
scripts/greetings-maven-2.20-J11.sh
scripts/greetings-maven-2.20.sh
scripts/greetings-tycho-2.20-J11.sh
scripts/greetings-tycho-2.20.sh

[eclipse/xtext#1539] enabled 2.20 examples

[eclipse/xtext#1539] enabled 2.20 examples

---

greetings-gradle/2.20.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.20.0-J11/org.xtext.example.mydsl.parent/gradlew
greetings-gradle/2.20.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.20.0/org.xtext.example.mydsl.parent/gradlew

update to gradle 5.6.1

---

.travis.yml
scripts/integrationtests-wizard.sh
scripts/integrationtests-xtend-examples.sh
scripts/integrationtests-xtext-examples.sh

splitted execution of integ tests

splitted execution of integ tests

---

domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.20.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

orbit 2019-12

---

greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.ui.tests/pom.xml
greetings-tycho/2.20.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0/org.xtext.example.mydsl.ui.tests/pom.xml

regenerated example with latest master

---

domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.ide/META-INF/MANIFEST.MF
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/DomainmodelParsingTest.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/OrganizeImportsTest.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/ValidationTests.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/XbaseIntegrationTest.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.ui.tests/pom.xml
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/FoldingTest.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/LabelProviderTest.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.ui/META-INF/MANIFEST.MF
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel/pom.xml
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.xtend
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/IssueCodes.java

updated 2.20 domain model

---

greetings-gradle/2.20.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.20.0/org.xtext.example.mydsl.parent/build.gradle

use xtext-gradle-plugin 2.0.8

---

.travis.yml
settings.xml

retry wizard tests

---

domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0/org.xtext.example.mydsl.parent/pom.xml
integrationtests/pom.xml

[eclipse/xtext#1553] update to tycho 1.5.0

[eclipse/xtext#1553] update to tycho 1.5.0

---

domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.20.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to asm 7.2

---

greetings-gradle/2.20.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.20.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties

update to gradle 5.6.3

---

domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0/org.xtext.example.mydsl.parent/pom.xml

update to tycho 1.5.1

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

fixed integ tests asm version

---

greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0-J11/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.20.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0/org.xtext.example.mydsl/pom.xml

regenerated from latest master

---

domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.20.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-gradle/2.20.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.20.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.20.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.20.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.20.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.20.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#1608] use final release 

[eclipse/xtext#1608] use final release 

---

greetings-maven/2.21.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.21.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0/org.xtext.example.mydsl.parent/pom.xml

regenerated 2.21 examples

---

domainmodel/2.21.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0/org.xtext.example.mydsl.parent/pom.xml
integrationtests/pom.xml

update to tycho 1.6.0

---

domainmodel/2.21.0/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/DomainmodelValidator.java

regenerated domainmodel example

regenerated domainmodel example

---

domainmodel/2.21.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.21.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.21.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

test with mwe 2.11.2.M3

---

greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.21.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to junit 5.6

---

domainmodel/2.21.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.21.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.21.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

recreated 2.21 projects

---

domainmodel/2.21.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.21.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-gradle/2.21.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.21.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.21.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.21.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.21.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.21.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#1684] update ref projects to latest release

[eclipse/xtext#1684] update ref projects to latest release

---

domainmodel/2.22.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.22.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.22.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#1685] regen examples

[eclipse/xtext#1685] regen examples

---

domainmodel/2.22.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.22.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.22.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

regenerated with orbit change

---

domainmodel/2.22.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.22.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.22.0/org.xtext.example.mydsl.parent/pom.xml
integrationtests/pom.xml

Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

[https://github.com/eclipse/xtext/issues/1732] Update to Tycho 1.7.0

---

greetings-tycho/2.22.0-J11/org.xtext.example.mydsl/build.properties
greetings-tycho/2.22.0/org.xtext.example.mydsl/build.properties

regenerated ref projects

---

domainmodel/2.22.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.22.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.22.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.22.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.22.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.22.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to mwe 2.11.3.M3

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

fixed build

---

domainmodel/2.22.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.22.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.22.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.22.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.22.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.22.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

regen with mwe 2.11.3

---

domainmodel/2.23.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.23.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.23.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

regenerated examples (orbit 2020-09)

regenerated examples (orbit 2020-09)

---

domainmodel/2.23.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/CodeMiningTest.xtend

regen example

---

.travis.yml
domainmodel/2.23.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml

build domain model with J11

---

domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.24.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update orbit & simrel to 2020-12

update orbit & simrel to 2020-12

---

domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.24.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to asm 9

---

domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/DomainmodelParsingTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/OrganizeImportsTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/ValidationTests.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/AutoEditTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/ContentAssistTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HighlightingTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HoverTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/HyperlinkingTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/OutlineTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/QuickfixTest.xtend

regen domain model example

---

domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui.tests/src/org/eclipse/xtext/example/domainmodel/ui/tests/CodeMiningTest.xtend
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/codemining/DomainmodelCodeMiningProvider.java

updated domain model

---

greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.24.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

regen examples junit 5 update

---

domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.tests/META-INF/MANIFEST.MF
greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.ui.tests/META-INF/MANIFEST.MF
greetings-tycho/2.24.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.24.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.24.0/org.xtext.example.mydsl.tests/META-INF/MANIFEST.MF
greetings-tycho/2.24.0/org.xtext.example.mydsl.ui.tests/META-INF/MANIFEST.MF
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

fixed & update of examples

---

settings.xml

cleanup settings.xml

---

domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel/pom.xml

updated domain model example

---

domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.24.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.24.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.24.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.24.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

mwe 2.12.0 final

---

integrationtests/org.eclipse.xtext.swtbot.tests/src/org/eclipse/xtext/swtbot/tests/XtextExamplesTest.java

run all  tests on project as we have a mix of xtend and java

run all  tests on project as we have a mix of xtend and java

---

domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.25.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.25.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

updated 2.25 examples

---

.travis.yml
domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.25.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#1885] use 2021-03 in wizard

[eclipse/xtext#1885] use 2021-03 in wizard

---

greetings-tycho/2.25.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.25.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

regen 2.25

---

greetings-gradle/2.12.0/build.gradle
greetings-gradle/2.14.0/build.gradle
greetings-gradle/2.15.0/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.16.0/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.17.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.17.0.M1/build.gradle
greetings-gradle/2.17.0/org.xtext.example.mydsl.parent/build.gradle

sunset jcenter

---

domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
greetings-tycho/2.25.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.25.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

asm update in reference projects

asm update in reference projects

---

domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.25.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.25.0/org.xtext.example.mydsl.parent/pom.xml

update to mwe 2.12.1 final

---

domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.25.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.25.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

update to junit 5.7.1 & final mwe

---

domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.25.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-gradle/2.25.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.25.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.25.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.25.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.25.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.25.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.25.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.25.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#1946] update to 2.25.0 releases

[eclipse/xtext#1946] update to 2.25.0 releases

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#1944] update orbit to 2021-06

[eclipse/xtext#1944] update orbit to 2021-06

---

.github/workflows/build.yml

[#166] test with ubuntu 18.04

---

greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

regenerated examples

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#1947] use 2021-06 in tps

[eclipse/xtext#1947] use 2021-06 in tps

---

.github/workflows/build.yml
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/AbstractSwtBotTest.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/JUnitViewAPI.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/MainMenuAPI.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/NewProjectWizardAPI.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/PackageExplorerAPI.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/PreferencesDialogAPI.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/RunConfigurationsDialogAPI.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/XtendFormatterPreferenceEditDialogAPI.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/internal/XtextSWTBot.java
integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/internal/XtextSWTBotShell.java
integrationtests/org.eclipse.xtext.swtbot.tests/src/org/eclipse/xtext/swtbot/tests/XtendExamplesTest.java
integrationtests/org.eclipse.xtext.swtbot.tests/src/org/eclipse/xtext/swtbot/tests/XtextExamplesTest.java
integrationtests/org.eclipse.xtext.swtbot.tests/src/org/eclipse/xtext/swtbot/tests/XtextNewProjectWizardTest.java

Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

[#166] Force focus after shell closing to fix Xvfb issues.

---

.github/workflows/build.yml

add tycho j8 build

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

revert use of staging in domain model

revert use of staging in domain model

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-maven/2.26.0-J11/org.xtext.example.mydsl/pom.xml
greetings-maven/2.26.0/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.26.0/org.xtext.example.mydsl/pom.xml

regen: exex plugin version 3.0.0

regen: exex plugin version 3.0.0

---

.github/workflows/build.yml

use v2 of java action

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update orbit to 2021-09

---

greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/build.gradle

workaround for gradle java 8 problem https://github.com/eclipse/xtext/issues/1976

workaround for gradle java 8 problem

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

regen examples

---

greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/build.gradle

cleanup ws

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.parent/pom.xml
integrationtests/org.eclipse.xtext.swtbot.testing/pom.xml
integrationtests/pom.xml

update to tycho 2.4

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

platform & orbit update for integ tests

platform & orbit update for integ tests

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl/pom.xml

regenerate examples with new exec call

regenerate examples with new exec call

---

.github/workflows/build.yml
scripts/domainmodel-2.26.sh
scripts/greetings-tycho-2.26-J11.sh

also build with tycho 2.5.0-SNAPSHOT & bump xvfb action

also build with tycho 2.5.0-SNAPSHOT & bump xvfb action

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

update to mwe 2.12.2.M1

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

update to asm 9.2

---

greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/build.gradle

update to xtext-gradle-plugin 2.0.9

update to xtext-gradle-plugin 2.0.9

---

greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/build.gradle

update plugin to 2.1.0

---

.github/workflows/build.yml

test with j17

---

.github/workflows/build.yml

test with tycho 2.6.0-SNAPSHOT

test with tycho 2.6.0-SNAPSHOT

---

greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/gradle/source-layout.gradle
greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/gradle/source-layout.gradle
greetings-tycho/2.26.0/org.xtext.example.mydsl.parent/pom.xml

regenerated with new xtext-gradle-plugin

regenerated with new xtext-gradle-plugin

---

greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties

update to gradle 7.3

---

greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

gson update

---

greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties

update to gradle 7.3.1

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

consume classgraph from xtext update site

consume classgraph from xtext update site

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

classgraph update

---

greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties

update to gradle 7.3.2

---

greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties

update to gradle 7.3.3

---

greetings-tycho/2.26.0/org.xtext.example.mydsl/pom.xml

remove j8 workaround

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to mwe(2) 2.12.2 release

update to mwe(2) 2.12.2 release

---

.github/workflows/build.yml
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.parent/pom.xml

[eclipse/xtext#2021] update to tycho 2.6.0

[eclipse/xtext#2021] update to tycho 2.6.0

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

switch to 2022-03

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

update to orbit 2022-03

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.ide/pom.xml
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-maven/2.26.0-J11/org.xtext.example.mydsl.ide/pom.xml
greetings-maven/2.26.0-J11/org.xtext.example.mydsl/pom.xml
greetings-maven/2.26.0/org.xtext.example.mydsl.ide/pom.xml
greetings-maven/2.26.0/org.xtext.example.mydsl/pom.xml

regen examples with bumped maven deps

regen examples with bumped maven deps

---

greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2031] update to GSON 2.8.9

[eclipse/xtext#2031] update to GSON 2.8.9

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

fix domainmodel log4j dependency

fix domainmodel log4j dependency

---

integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/PackageExplorerAPI.java
integrationtests/org.eclipse.xtext.swtbot.tests/src/org/eclipse/xtext/swtbot/tests/XtextNewProjectWizardTest.java

added explicit refresh

---

domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.26.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-gradle/2.26.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.26.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.26.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.26.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.26.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.26.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.26.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#2041] update to 2.26.0 release

[eclipse/xtext#2041] update to 2.26.0 release

---

.github/workflows/build.yml

Bump actions/checkout from 2 to 3

Bump actions/checkout from 2 to 3

---

.github/workflows/build.yml

[eclipse/xtext#2041] test with tycho 3.0

[eclipse/xtext#2041] test with tycho 3.0

---

.github/workflows/build.yml

bmp xvfb action

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

use mwe release version

---

Jenkinsfile
domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target
integrationtests/pom.xml
scripts/domainmodel-2.27.sh
scripts/greetings-tycho-2.27.sh
scripts/integrationtests-xtext-examples.sh

add Jenkinsfile

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-maven/2.27.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.27.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.27.0/org.xtext.example.mydsl.parent/pom.xml

[eclipse/xtext-core#1851] test disabling more repos to avoid maven-default-http-blocker warnings

[eclipse/xtext-core#1851] test disabling more repos to avoid maven-default-http-blocker warnings

---

projects.Jenkinsfile

add Jenkinsfile for projects

---

.github/workflows/build-integtests-wizard.yml
.github/workflows/build-integtests-xtend.yml
.github/workflows/build-integtests-xtext.yml
.github/workflows/build.yml

separate project and test builds

separate project and test builds

---

integtests.Jenkinsfile
projects.Jenkinsfile

update to maven 3.8.5

---

greetings-gradle/2.27.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.27.0/org.xtext.example.mydsl.parent/build.gradle

update to xtext-gradle-plugin 3.0.2

update to xtext-gradle-plugin 3.0.2

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#2038] use 2022-06 in wizard & dm example

[eclipse/xtext#2038] use 2022-06 in wizard & dm example

---

greetings-tycho/2.27.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

fix for junit 4.12/4.13 update

fix for junit 4.12/4.13 update

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

bump apache.commons.cli

---

greetings-gradle/2.27.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.27.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties

update to gradle 7.4.2

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.27.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.27.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1

[eclipse/xtext#2054] bootstrap against mwe 2.13.0.M1

---

scripts/integrationtests-wizard.sh
scripts/integrationtests-xtend-examples.sh
scripts/integrationtests-xtext-examples.sh

add EXTRA_ARGS to integ tests too

add EXTRA_ARGS to integ tests too

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.parent/pom.xml
integrationtests/pom.xml

update to tycho 2.7.1

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/CompilerTest.xtend

updated example

---

.github/workflows/build.yml

bump setup-java action to v3

---

integtests.Jenkinsfile
projects.Jenkinsfile

[eclipse/xtext#2057] update to centos-8 agent

[eclipse/xtext#2057] update to centos-8 agent

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.27.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

[eclipse/xtext#2053] Update to ASM 9.3 [eclipse/xtext#2039] Update to Orbit 2022-06

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.ide/pom.xml
domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.27.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

asm cleanup

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.27.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.27.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to MWE 2.13.0.M2

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.parent/pom.xml
integrationtests/pom.xml

[eclipse/xtext#2060] update to tycho 2.7.2

[eclipse/xtext#2060] update to tycho 2.7.2

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.parent/pom.xml
integrationtests/pom.xml

update to tycho 2.7.3

---

integtests.Jenkinsfile

run job a little later

---

domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.27.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.27.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.27.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.27.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

update to mwe 2.13.0 release

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target
integrationtests/org.eclipse.xtext.swtbot.testing/META-INF/MANIFEST.MF

update to 2022-06

---

domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#2068] update tp to 2022-09

[eclipse/xtext#2068] update tp to 2022-09

---

domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.parent/pom.xml
integrationtests/pom.xml

update to tycho 2.7.4

---

domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2071] update to orbit 2022-09

[eclipse/xtext#2071] update to orbit 2022-09

---

greetings-maven/2.28.0-J11/org.xtext.example.mydsl/pom.xml
greetings-maven/2.28.0/org.xtext.example.mydsl/pom.xml

bump maven-assembly-plugin

---

domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.ide/pom.xml

more bumps

---

domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.tests/pom.xml
domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.ui.tests/pom.xml
greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.parent/pom.xml

dont override managed version

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target
integrationtests/org.eclipse.xtext.swtbot.testing/META-INF/MANIFEST.MF
integrationtests/pom.xml

[#272] bump swtbot to 4.0.0

---

greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.28.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2081] update to gson 2.9.0

[eclipse/xtext#2081] update to gson 2.9.0

---

integtests.Jenkinsfile
projects.Jenkinsfile

update to maven 3.8.6

---

domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.parent/pom.xml

[eclipse/xtext#2083] use new way for source features in tycho 2.7.x+ builds

[eclipse/xtext#2083] use new way for source features in tycho 2.7.x+ builds

---

greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

#286 adapt to latest platform changes breaking orbit

#286 adapt to latest platform changes breaking orbit

---

greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.tests/META-INF/MANIFEST.MF
greetings-tycho/2.28.0-J11/org.xtext.example.mydsl.ui.tests/META-INF/MANIFEST.MF
greetings-tycho/2.28.0/org.xtext.example.mydsl.tests/META-INF/MANIFEST.MF
greetings-tycho/2.28.0/org.xtext.example.mydsl.ui.tests/META-INF/MANIFEST.MF

test changes to junit5 deps

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target
integrationtests/pom.xml

remove dead pde api tools

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.parent/pom.xml
integrationtests/pom.xml

[eclipse/xtext#2096] update to tycho 2.7.5

[eclipse/xtext#2096] update to tycho 2.7.5

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

use 2022-12

---

.github/workflows/build.yml

run tycho 30 builds with j17 only

run tycho 30 builds with j17 only

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.29.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

[eclipse/xtext#2089] Update to Orbit 2022-12 incl new classgraph & gson

---

.github/workflows/build.yml

 fix tycho 30, test tycho 3.1

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.tests/META-INF/MANIFEST.MF
domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel/META-INF/MANIFEST.MF
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.29.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2104] update to asm 9.4

[eclipse/xtext#2104] update to asm 9.4

---

.github/workflows/build.yml

test with tycho 4.0

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

add apache.commons.logging needed by batik needed by platform

add apache.commons.logging needed by batik needed by platform

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.29.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.29.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#2106] Update to MWE 2.14.0.M1

[eclipse/xtext#2106] Update to MWE 2.14.0.M1

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

fix mwe version for integ tests

fix mwe version for integ tests

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.29.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

use fixed asm 9.4 version from orbit m3

use fixed asm 9.4 version from orbit m3

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.29.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2112] Fix Orbit signing problem

[eclipse/xtext#2112] Fix Orbit signing problem

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.29.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2112] switch back to orbit 2022-12

[eclipse/xtext#2112] switch back to orbit 2022-12

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.29.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.29.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2107] update to mwe 2.14.0 release

[eclipse/xtext#2107] update to mwe 2.14.0 release

---

domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.29.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-gradle/2.29.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.29.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.29.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.29.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.29.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.29.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.29.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to 2.29.0 release

---

.github/workflows/build.yml

update to tycho 3.0.1

---

.github/workflows/build.yml
greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.ui.tests/META-INF/MANIFEST.MF
greetings-tycho/2.30.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.30.0/org.xtext.example.mydsl.ui.tests/META-INF/MANIFEST.MF

[eclipse/xtext#2102] switch to Tycho 3.0.1

[eclipse/xtext#2102] switch to Tycho 3.0.1

---

domainmodel/2.30.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.30.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2118] update to orbit 2023-03

[eclipse/xtext#2118] update to orbit 2023-03

---

greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.30.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2131] update to gson 2.10

[eclipse/xtext#2131] update to gson 2.10

---

domainmodel/2.30.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.30.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.30.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#2126] bump reload4j

[eclipse/xtext#2126] bump reload4j

---

greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.30.0/org.xtext.example.mydsl.parent/pom.xml

[eclipse/xtext#2134] replace compiler.tool+apt with batch

[eclipse/xtext#2134] replace compiler.tool+apt with batch

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

update to gson 2.10.1

---

domainmodel/2.30.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

update domainmodel from master

update domainmodel from master

---

.github/workflows/build.yml
greetings-tycho/2.30.0/org.xtext.example.mydsl.parent/pom.xml

update to tycho 3.0.2

---

greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.30.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

regen gson 2.10.1

---

.github/workflows/build.yml
greetings-tycho/2.30.0/org.xtext.example.mydsl.parent/pom.xml

update to tycho 3.0.3

---

greetings-gradle/2.30.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.30.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties

[eclipse/xtext#2138] update to gradle 7.6.1

[eclipse/xtext#2138] update to gradle 7.6.1

---

domainmodel/2.30.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
domainmodel/2.30.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-gradle/2.30.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.30.0/org.xtext.example.mydsl.parent/build.gradle
greetings-maven/2.30.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.30.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.30.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.30.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.30.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#2140] update to 2.30 release

[eclipse/xtext#2140] update to 2.30 release

---

.project
domainmodel/2.31.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.31.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[#2141] Prepare Wizard for 2023-06

[#2141] Prepare Wizard for 2023-06

---

greetings-tycho/2.31.0/org.xtext.example.mydsl.parent/pom.xml

update to tycho 3.0.4 in wizard

update to tycho 3.0.4 in wizard

---

domainmodel/2.31.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.31.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.31.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[#2142] update to orbit 2023-06

[#2142] update to orbit 2023-06

---

greetings-tycho/2.31.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.31.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2197] Wizard: Update to Junit 5.9.2

[eclipse/xtext#2197] Wizard: Update to Junit 5.9.2

---

integtests.Jenkinsfile
projects.Jenkinsfile

disable paralell stages and jenkins cannot handle it anymore

disable paralell stages and jenkins cannot handle it anymore

---

.github/workflows/build.yml
integtests.Jenkinsfile
projects.Jenkinsfile

Run DomainModel & Builds with J17

Run DomainModel & Builds with J17

---

greetings-gradle/2.31.0-J11/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.31.0-J11/org.xtext.example.mydsl.parent/gradlew
greetings-gradle/2.31.0/org.xtext.example.mydsl.parent/gradle/wrapper/gradle-wrapper.properties
greetings-gradle/2.31.0/org.xtext.example.mydsl.parent/gradlew

update to gradle 8.1.1

---

greetings-tycho/2.31.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.31.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

dont explicitely pass junit5 version

dont explicitely pass junit5 version

---

.github/workflows/build.yml

use maven 3.9.1 with tycho 4.0

use maven 3.9.1 with tycho 4.0

---

domainmodel/2.32.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.32.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[eclipse/xtext#2693] update to Eclipse 2023-09

[eclipse/xtext#2693] update to Eclipse 2023-09

---

.github/workflows/build.yml
greetings-tycho/2.32.0/org.xtext.example.mydsl.parent/pom.xml

Update to Tycho 3.0.5. 
See eclipse/xtext#2709

Update to Tycho 3.0.5. 

---

domainmodel/2.32.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.32.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.32.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.32.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.32.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.32.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

Guice & Guava update

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2726] update to guava 32.1.0

[eclipse/xtext#2726] update to guava 32.1.0

---

.github/workflows/build.yml

test with tycho 4 release and 5 snapshots

test with tycho 4 release and 5 snapshots

---

greetings-gradle/2.32.0-J11/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.32.0-J11/org.xtext.example.mydsl.parent/gradle/source-layout.gradle
greetings-gradle/2.32.0-J11/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/build.gradle
greetings-gradle/2.32.0/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.32.0/org.xtext.example.mydsl.parent/gradle/source-layout.gradle
greetings-gradle/2.32.0/org.xtext.example.mydsl.parent/org.xtext.example.mydsl/build.gradle

fixed gradle 8.2 deprecations

---

integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

update to junit 5.10

---

greetings-tycho/2.32.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.32.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

adapt to latest orbit changes

---

domainmodel/2.32.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.32.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.32.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.32.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.32.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.32.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to mwe 2.15.0.M2

---

.github/workflows/build.yml

update to tycho 4.0.1 final

---

domainmodel/2.32.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
domainmodel/2.32.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.32.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.32.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.32.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.32.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

update to mwe 2.15.0.M3

---

domainmodel/2.33.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.33.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target

[#2754] prepare 2023-12 tps

---

domainmodel/2.33.0/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
greetings-tycho/2.33.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.33.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

[eclipse/xtext#2754] update to orbit 2023-12

[eclipse/xtext#2754] update to orbit 2023-12

---

.github/workflows/build.yml
domainmodel/2.33.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml

[eclipse/xtext#2849] ditch old tycho 2.7.5 builds

[eclipse/xtext#2849] ditch old tycho 2.7.5 builds

---

domainmodel/2.34.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-tycho/2.34.0-J11/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.34.0/org.xtext.example.mydsl.parent/pom.xml

see
https://github.com/eclipse/xtext/pull/2910
https://github.com/eclipse/xtext/issues/2909

update for xtext.logging versionRange 0.0.0 in extraRequirements

---

greetings-tycho/2.37.0-J11/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.37.0-J21/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
greetings-tycho/2.37.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target
integrationtests/org.eclipse.xtext.integrationtests.target/org.eclipse.xtext.integrationtests.target.target

See https://github.com/eclipse/xtext/issues/3213

Guava and junit.org need updates

---

integrationtests/org.eclipse.xtext.swtbot.testing/src/org/eclipse/xtext/swtbot/testing/api/PackageExplorerAPI.java

delete projects programmatically

---

domainmodel/2.38.0/org.eclipse.xtext.example.domainmodel/pom.xml
greetings-tycho/2.38.0-J21/org.xtext.example.mydsl/pom.xml
greetings-tycho/2.38.0/org.xtext.example.mydsl/pom.xml

See https://github.com/eclipse-xtext/xtext/issues/3304

add generator.dependencies in exec-maven-plugin

---

domainmodel/2.40.0/org.eclipse.xtext.example.domainmodel.releng/pom.xml
greetings-gradle/2.40.0-J21/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.40.0-J21/org.xtext.example.mydsl.parent/gradlew
greetings-gradle/2.40.0/org.xtext.example.mydsl.parent/build.gradle
greetings-gradle/2.40.0/org.xtext.example.mydsl.parent/gradlew
greetings-maven/2.40.0-J21/org.xtext.example.mydsl.parent/pom.xml
greetings-maven/2.40.0/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.40.0-J21/org.xtext.example.mydsl.parent/pom.xml
greetings-tycho/2.40.0/org.xtext.example.mydsl.parent/pom.xml

See https://github.com/eclipse-xtext/xtext/issues/3398

use the new central maven snapshot repository
